// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package goshort

import (
	"context"
)

const getURL = `-- name: GetURL :one
SELECT id FROM urls WHERE url = ?
`

func (q *Queries) GetURL(ctx context.Context, url string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getURL, url)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertURL = `-- name: InsertURL :exec
INSERT INTO urls (url) VALUES (?)
`

func (q *Queries) InsertURL(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, insertURL, url)
	return err
}
