// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package store

import (
	"context"
)

const getURL = `-- name: GetURL :one
SELECT url FROM urls WHERE id = ?
`

func (q *Queries) GetURL(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getURL, id)
	var url string
	err := row.Scan(&url)
	return url, err
}

const insertURL = `-- name: InsertURL :one
INSERT INTO urls (url) VALUES (?)
RETURNING id
`

func (q *Queries) InsertURL(ctx context.Context, url string) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertURL, url)
	var id int64
	err := row.Scan(&id)
	return id, err
}
